// OpenNext generates .open-next/worker.js during the Cloudflare build.
// This wrapper keeps the normal fetch handler and adds Cloudflare cron support.
// @ts-ignore Generated by opennextjs-cloudflare build.
import { default as nextWorker } from "./.open-next/worker.js";

type WorkerEnv = {
  CRON_SECRET?: string;
  CLOUDFLARE_INTERNAL_ORIGIN?: string;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
};

type ScheduledEvent = {
  cron: string;
};

async function runCronRoute(path: string, env: WorkerEnv, ctx: WorkerExecutionContext) {
  const origin = (env.CLOUDFLARE_INTERNAL_ORIGIN || "https://sokaigelek.hu").replace(/\/$/, "");
  const url = new URL(`${origin}${path}`);
  url.searchParams.set("secret", env.CRON_SECRET || "");

  const response = await nextWorker.fetch(
    new Request(url, { method: "GET", headers: { "user-agent": "cloudflare-cron/1" } }),
    env,
    ctx,
  );

  if (!response.ok) {
    console.error("cloudflare_cron_failed", { path, status: response.status });
  }
}

function getBudapestTime() {
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: "Europe/Budapest",
    weekday: "short",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).formatToParts(new Date());
  const values = new Map(parts.map((part) => [part.type, part.value]));
  return {
    weekday: values.get("weekday") || "",
    hour: values.get("hour") || "",
    minute: values.get("minute") || "",
  };
}

export default {
  fetch: nextWorker.fetch,

  async scheduled(controller: ScheduledEvent, env: WorkerEnv, ctx: WorkerExecutionContext) {
    if (controller.cron !== "*/10 * * * *") {
      console.warn("cloudflare_cron_unmapped", { cron: controller.cron });
      return;
    }

    const time = getBudapestTime();
    const paths = ["/api/cron/auto-articles"];

    if (time.hour === "05" && time.minute === "30") {
      paths.push("/api/cron/auto-topic-discovery");
    }
    if (time.hour === "03" && time.minute === "00") {
      paths.push("/api/cron/cleanup-chat-sessions");
    }
    if (time.minute === "00") {
      paths.push("/api/cron/brevo-sync-subscribers");
      if (["Tue", "Wed", "Thu"].includes(time.weekday) && time.hour === "14") {
        paths.push("/api/cron/brevo-digest");
      }
    }

    ctx.waitUntil(Promise.all(paths.map((path) => runCronRoute(path, env, ctx))));
  },
};
